apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: get-namespaces
rules:
- apiGroups: [""] #v1
  resources: ["namespaces", "pods", "services"]
  verbs: ["get","watch","list"]
