apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cgi-app.fullname" . }}
  labels:
    {{- include "cgi-app.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
  